name: randevum
description: White-label appointment management system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & Routing
  get: ^4.6.6

  # Networking
  dio: ^5.4.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1

  # Storage
  shared_preferences: ^2.2.2

  # UI
  cached_network_image: ^3.3.1

  # Utils
  connectivity_plus: ^5.0.2
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
